import React, { useState } from 'react';
import MovingCard from './components/MovingCard';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import Modal from './components/Modal';
import Notification from './features/notification/Notification';
import { useDispatch } from 'react-redux';
import { addNotification } from './features/dataSlice';
import { useSelector } from 'react-redux';
import Button from './components/Button';
import Dropdown from './components/Dropdown';
import NavBar from './components/NavBar';
import Home from './pages/Home';

export const App = () => {
  const [isOpen, setIsOpen] = useState(false);
  const notifications = useSelector(state => state?.data.notifications);
  const dispatch = useDispatch();

  const onClick = () => {
    // setIsOpen(prev => !prev);
    const randomIndex = Math.floor(Math.random() * 10000);
    const notification = {
      id: randomIndex,
      icon: <></>,
      text: "notification"
    }
    dispatch(addNotification(notification));
  }

  return (
    <>
      <header>
        <title>Sans-Soucis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
        {/* <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" /> */}
      </header>

      <body className='text-slate-100 bg-gradient-to-t from-slate-900 via-slate-950 to-slate-950'>
        <main className=''>
          <BrowserRouter>
            <NavBar />
              <div className='min-h-screen'>
                <div className='container mx-auto py-10'>
                  <Routes>
                    <Route path="/" element={<Home />} />
                  </Routes>
                </div>
              </div>
          </BrowserRouter>
          {/* <div className='h-screen'>
            <Dropdown />
            <Button text='connexion' onClick={onClick} />
          </div>
          <div className="grid w-full place-content-center">
            {isOpen && <Modal isOpen={isOpen} setIsOpen={setIsOpen} />}
          </div>
          <div className="flex flex-col gap-1 w-72 fixed top-2 right-2 z-50 pointer-events-none">
            <AnimatePresence>
              {notifications.map(notification => (
                <Notification key={notification.id} {...notification} />
              ))}
            </AnimatePresence>
          </div> */}
        </main>
      </body>
    </>
  );
}

export default App;
